// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/Users/matthias/Documents/Code/Web/sitepitch/node_modules/.pnpm/eve@0.20.0_ai@7.0.16_zod@4.4.3__jiti@2.7.0_microsandbox@0.6.4_vite@8.1.3_@types+node@24.13.2_esbuild@0.27.0_jiti@2.7.0_/node_modules/eve/dist/src/internal/workflow/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve73686164636e2d75692d74656d706c617465_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
