// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/tools/get_audit_context.ts";
import * as module_2 from "../../agent/tools/save_audit_output.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "tools/get_audit_context.ts": module_1,
                  "tools/save_audit_output.ts": module_2
                })
            })
    })
});

export default moduleMap;
